repos:

# - repo: ...

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [code, fix, feat] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]