version: 2.1

jobs:
  generate-pdf:
    docker:
      - image: matiusz/songbook:latest
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Generate HK PDF
          command: python3 -m songbook.apps.create_pdf
          environment:
            SONGBOOK_DATA_DIR: hk-songbook
      - store_artifacts:
          path: songbook.pdf
          destination: hk-songbook.pdf
      - store_artifacts:
          path: songbook-py.log
          destination: hk-songbook.log
      - run:
          name: Generate 111 ADH PDF
          command: python3 -m songbook.apps.create_pdf
          environment:
            SONGBOOK_DATA_DIR: spiewnik111adh
      - store_artifacts:
          path: songbook.pdf
          destination: spiewnik111adh.pdf
      - store_artifacts:
          path: songbook-py.log
          destination: spiewnik111adh.log

workflows:
  build-and-test:
    jobs:
      - generate-pdf
