version: 2.1

jobs:
  generate-pdf:
    docker:
      - image: mathek/songbook:latest
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Generate PDF
          command: python3 songbook_pdf.py
      - store_artifacts:
          path: songbook.pdf

workflows:
  build-and-test:
    jobs:
      - generate-pdf
