version: 2.1

jobs:
  generate-pdf:
    docker:
      - image: mathek/songbook:latest
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Update MiKTeX
          command: miktex --admin fndb refresh
      - run:
          name: Generate PDF
          command: python3 songbook_pdf.py
      - store_artifacts:
          path: songbook.pdf
      - store_artifacts:
          path: /root/.miktex/texmfs/data/miktex/log/pdflatex.log
      - store_artifacts:
          path: songbook-py.log

workflows:
  build-and-test:
    jobs:
      - generate-pdf
