version: 2.1

jobs:
  generate-pdf:
    docker:
      - image: mathek/songbook:latest
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Update Apt
          command: apt --update
      - run:
          name: Update MiKTeX
          command: initexmf --admin --set-config-value=[MPM]AutoInstall=1     && mpm --admin --update-db     && initexmf --admin --update-fndb # buildkit
      - run:
          name: Generate PDF
          command: python3 songbook_pdf.py
      - store_artifacts:
          path: songbook.pdf
      - store_artifacts:
          path: /root/.miktex/texmfs/data/miktex/log/pdflatex.log
      - store_artifacts:
          path: songbook-py.log
      - store_artifacts:
          path: /root/.miktex/texmfs/data/miktex/log/initexmf.log

workflows:
  build-and-test:
    jobs:
      - generate-pdf
