version: 2.1

jobs:
  generate-pdf:
    docker:
      - image: matiusz/songbook:latest
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Generate PDF
          command: python3 -m apps.create_pdf
      - store_artifacts:
          path: songbook.pdf
      - store_artifacts:
          path: songbook-py.log

workflows:
  build-and-test:
    jobs:
      - generate-pdf
