name: build-pdf
on:
  push:
    branches:
      - hk-songbook
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container: matiusz/songbook:latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: mmajewsk/songbook
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./app
      - name: Generate HK PDF
        run: python3 -m songbook.apps.create_pdf
        env:
          SONGBOOK_DATA_DIR: hk-songbook
          SONGBOOK_TITLE: hk-songbook

      - name: Archive HK PDF
        uses: actions/upload-artifact@v4
        with:
          name: hk-songbook
          path: app/hk-songbook.pdf
          if-no-files-found: error