name: build-pdf
on:
  push:
    branches:
      - hk-songbook
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container: matiusz/songbook:latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: matiusz/songbook
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./app
      - name: ls
        run: ls
      - name: Generate HK PDF
        run: python3 -m songbook.apps.create_pdf
        env:
          SONGBOOK_DATA_DIR: hk-songbook

      - name: Generate 111 ADH PDF
        run: python3 -m songbook.apps.create_pdf
        env:
          SONGBOOK_DATA_DIR: spiewnik111adh

      - name: Archive HK PDF
        uses: actions/upload-artifact@v4
        with:
          name: hk-songbook
          path: hk-songbook.pdf

      - name: Archive 111 ADH PDF
        uses: actions/upload-artifact@v4
        with:
          name: spiewnik111adh
          path: spiewnik111adh.pdf